/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ABeautifulGame.glb 
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ABeautifulGame.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.King_B.geometry} material={materials.King_Black} position={[-0.031, 0.017, 0.22]} />
      <mesh geometry={nodes.King_W.geometry} material={materials.King_White} position={[-0.032, 0.017, -0.22]} />
      <mesh geometry={nodes.Queen_B.geometry} material={materials.Queen_Black} position={[0.031, 0.018, 0.22]} />
      <mesh geometry={nodes.Queen_W.geometry} material={materials.Queen_White} position={[0.031, 0.017, -0.22]} />
      <mesh geometry={nodes.Chessboard.geometry} material={materials.Chessboard} />
      <mesh geometry={nodes.Pawn_Body_W1.geometry} material={materials.Pawn_Body_White} position={[0.218, 0.015, -0.156]}>
        <mesh geometry={nodes.Pawn_Top_W1.geometry} material={materials.Pawn_Top_White} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_W2.geometry} material={materials.Pawn_Body_White} position={[0.156, 0.015, -0.156]}>
        <mesh geometry={nodes.Pawn_Top_W2.geometry} material={materials.Pawn_Top_White} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_W3.geometry} material={materials.Pawn_Body_White} position={[0.094, 0.015, -0.094]}>
        <mesh geometry={nodes.Pawn_Top_W3.geometry} material={materials.Pawn_Top_White} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_W4.geometry} material={materials.Pawn_Body_White} position={[0.031, 0.015, -0.031]}>
        <mesh geometry={nodes.Pawn_Top_W4.geometry} material={materials.Pawn_Top_White} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_W5.geometry} material={materials.Pawn_Body_White} position={[-0.031, 0.015, -0.156]}>
        <mesh geometry={nodes.Pawn_Top_W5.geometry} material={materials.Pawn_Top_White} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_W6.geometry} material={materials.Pawn_Body_White} position={[-0.094, 0.015, -0.156]}>
        <mesh geometry={nodes.Pawn_Top_W6.geometry} material={materials.Pawn_Top_White} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_W7.geometry} material={materials.Pawn_Body_White} position={[-0.156, 0.015, -0.156]}>
        <mesh geometry={nodes.Pawn_Top_W7.geometry} material={materials.Pawn_Top_White} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_W8.geometry} material={materials.Pawn_Body_White} position={[-0.219, 0.015, -0.156]}>
        <mesh geometry={nodes.Pawn_Top_W8.geometry} material={materials.Pawn_Top_White} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_B1.geometry} material={materials.Pawn_Body_Black} position={[-0.219, 0.015, 0.156]}>
        <mesh geometry={nodes.Pawn_Top_B1.geometry} material={materials.Pawn_Top_Black} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_B2.geometry} material={materials.Pawn_Body_Black} position={[-0.157, 0.015, 0.156]}>
        <mesh geometry={nodes.Pawn_Top_B2.geometry} material={materials.Pawn_Top_Black} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_B3.geometry} material={materials.Pawn_Body_Black} position={[-0.094, 0.015, 0.156]}>
        <mesh geometry={nodes.Pawn_Top_B3.geometry} material={materials.Pawn_Top_Black} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_B4.geometry} material={materials.Pawn_Body_Black} position={[-0.031, 0.015, 0.094]}>
        <mesh geometry={nodes.Pawn_Top_B4.geometry} material={materials.Pawn_Top_Black} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_B5.geometry} material={materials.Pawn_Body_Black} position={[0.031, 0.015, 0.156]}>
        <mesh geometry={nodes.Pawn_Top_B5.geometry} material={materials.Pawn_Top_Black} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_B6.geometry} material={materials.Pawn_Body_Black} position={[0.094, 0.015, 0.156]}>
        <mesh geometry={nodes.Pawn_Top_B6.geometry} material={materials.Pawn_Top_Black} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_B7.geometry} material={materials.Pawn_Body_Black} position={[0.156, 0.015, 0.156]}>
        <mesh geometry={nodes.Pawn_Top_B7.geometry} material={materials.Pawn_Top_Black} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Pawn_Body_B8.geometry} material={materials.Pawn_Body_Black} position={[0.219, 0.015, 0.156]}>
        <mesh geometry={nodes.Pawn_Top_B8.geometry} material={materials.Pawn_Top_Black} position={[-0.031, -0.015, 0.031]} />
      </mesh>
      <mesh geometry={nodes.Castle_B1.geometry} material={materials.Castle_Black} position={[-0.219, 0.018, 0.22]} />
      <mesh geometry={nodes.Castle_B2.geometry} material={materials.Castle_Black} position={[0.22, 0.018, 0.22]} />
      <mesh geometry={nodes.Castle_W1.geometry} material={materials.Castle_White} position={[0.22, 0.017, -0.22]} />
      <mesh geometry={nodes.Castle_W2.geometry} material={materials.Castle_White} position={[-0.219, 0.017, -0.22]} />
      <mesh geometry={nodes.Knight_B1.geometry} material={materials.Knight_Black} position={[-0.157, 0.017, 0.22]} />
      <mesh geometry={nodes.Knight_B2.geometry} material={materials.Knight_Black} position={[0.158, 0.017, 0.22]} />
      <mesh geometry={nodes.Knight_W1.geometry} material={materials.Knight_White} position={[0.158, 0.017, -0.221]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Knight_W2.geometry} material={materials.Knight_White} position={[-0.157, 0.017, -0.22]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Bishop_B1.geometry} material={materials.Bishop_Black} position={[-0.094, 0.017, 0.219]} />
      <mesh geometry={nodes.Bishop_B2.geometry} material={materials.Bishop_Black} position={[0.09, 0.017, 0.22]} />
      <mesh geometry={nodes.Bishop_W1.geometry} material={materials.Bishop_White} position={[0.09, 0.017, -0.218]} />
      <mesh geometry={nodes.Bishop_W2.geometry} material={materials.Bishop_White} position={[-0.094, 0.017, -0.221]} />
    </group>
  )
}

useGLTF.preload('/ABeautifulGame.glb')
